<<<<<<< HEAD
# Generated by Django 3.1.3 on 2020-12-28 23:21
=======
# Generated by Django 3.1.3 on 2020-12-23 13:26
>>>>>>> 945338805ba4d4ee8003d38a76152f57da8af184

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
<<<<<<< HEAD
                ('identifier', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('topic', models.CharField(blank=True, max_length=300, null=True)),
=======
                (
                    "identifier",
                    models.CharField(
                        max_length=45, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "topic",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "first_id_message",
                    models.CharField(
                        blank=True, default="0", max_length=45, null=True
                    ),
                ),
                (
                    "last_id_message",
                    models.CharField(
                        blank=True, default="0", max_length=45, null=True
                    ),
                ),
>>>>>>> 945338805ba4d4ee8003d38a76152f57da8af184
            ],
            options={
                'verbose_name': 'Channel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'ModelReference',
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('identifiant', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Server',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('identifiant', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'User',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
<<<<<<< HEAD
                ('identifiant', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.channel')),
                ('mentions', models.ManyToManyField(related_name='_message_mentions_+', to='api.Message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
=======
                (
                    "identifiant",
                    models.CharField(
                        max_length=45, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("date", models.DateField()),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.channel",
                    ),
                ),
                (
                    "references",
                    models.ManyToManyField(
                        related_name="_message_references_+", to="api.Message"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.user",
                    ),
                ),
>>>>>>> 945338805ba4d4ee8003d38a76152f57da8af184
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
<<<<<<< HEAD
                ('link_md5', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('link_content', models.URLField(blank=True, max_length=400, null=True)),
                ('links', models.ManyToManyField(related_name='messages', to='api.Message')),
=======
                (
                    "link_md5",
                    models.CharField(
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "link_content",
                    models.URLField(blank=True, max_length=400, null=True),
                ),
                (
                    "links",
                    models.ManyToManyField(
                        related_name="messages", to="api.Message"
                    ),
                ),
>>>>>>> 945338805ba4d4ee8003d38a76152f57da8af184
            ],
            options={
                'verbose_name': 'Link',
                'ordering': ['link_content'],
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.server'),
        ),
    ]
