# Generated by Django 3.1.3 on 2020-12-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="link_content",
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
