# Generated by Django 3.1.3 on 2020-12-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="identifiant",
            new_name="identifier",
        ),
        migrations.RenameField(
            model_name="server",
            old_name="identifiant",
            new_name="identifier",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="identifiant",
            new_name="identifier",
        ),
    ]
