# Generated by Django 3.1.3 on 2020-12-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20201216_1027"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="link_md5",
            field=models.CharField(
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
