# Generated by Django 3.1.7 on 2021-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_auto_20210222_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nb_min_user_messages',
            field=models.IntegerField(null=True),
        ),
    ]
