name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        python-version: [3.6, 3.7, 3.8]
        include:
          - db: mysql
            db_port: 3306
    services:
        mysql:
            image: mysql:8.0
            env:
              MYSQL_ROOT_PASSWORD: MOTDEPASSE1234
              MYSQL_USER: user
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: digdiscord
            ports:
                - 3306:3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 172.18.0.1 --port 3306 -uroot -ppassword -e "SHOW DATABASES"
 
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DB: digdiscord_test
        DB_HOST: 172.18.0.1
        DB_PORT: 3306
        DB_PASSWORD: MOTDEPASSE1234 
        DB_USER: user
        DJANGO_SETTINGS_MODULE: DigDiscord.settings.deploy_ci
      run: |
         cd DigDiscord &&
         python ./manage.py migrate --fake &&
         python manage.py test
